import type { IntakeFormItem } from "@/types";

export const INTAKE_FORMS_CATALOG: IntakeFormItem[] = [
  // ── Category 1: Registration & Administration ─────────────────────────────
  {
    id: "new_patient",
    name: "new_patient_form",
    label: "New Patient Form",
    category: "Registration & Administration",
    icon: "🧑‍⚕️",
    description: "Full name, date of birth, national ID, address, phone.",
  },
  {
    id: "insurance",
    name: "insurance_form",
    label: "Insurance Information",
    category: "Registration & Administration",
    icon: "🛡️",
    description: "Insurance provider, card/policy number, card photo upload.",
  },
  {
    id: "emergency_contact",
    name: "emergency_contact_form",
    label: "Emergency Contact",
    category: "Registration & Administration",
    icon: "📞",
    description: "Emergency contact name, relationship, and phone number.",
  },
  {
    id: "billing_policy",
    name: "billing_policy_form",
    label: "Billing Policy",
    category: "Registration & Administration",
    icon: "💳",
    description: "Payment policy acknowledgment and cancellation terms.",
  },
  {
    id: "patient_referral",
    name: "patient_referral_form",
    label: "Patient Referral",
    category: "Registration & Administration",
    icon: "📋",
    description: "Referring doctor, originating clinic, referral document upload.",
  },

  // ── Category 2: Medical & Clinical History ────────────────────────────────
  {
    id: "medical_history",
    name: "medical_history_form",
    label: "General Medical History",
    category: "Medical & Clinical History",
    icon: "🏥",
    description: "Diabetes, hypertension, heart disease, asthma, and other conditions.",
  },
  {
    id: "family_history",
    name: "family_history_form",
    label: "Family History",
    category: "Medical & Clinical History",
    icon: "👨‍👩‍👧",
    description: "Hereditary conditions: cancer, stroke, blood disorders.",
  },
  {
    id: "medications",
    name: "medications_form",
    label: "Current Medications",
    category: "Medical & Clinical History",
    icon: "💊",
    description: "Medication name, dose, frequency — multiple entries.",
  },
  {
    id: "allergy",
    name: "allergy_form",
    label: "Allergy Intake",
    category: "Medical & Clinical History",
    icon: "⚠️",
    description: "Drug allergies, food allergies, and reaction type.",
  },
  {
    id: "social_history",
    name: "social_history_form",
    label: "Social History",
    category: "Medical & Clinical History",
    icon: "🧑‍🤝‍🧑",
    description: "Smoking, alcohol use, and occupation.",
  },
  {
    id: "chief_complaint",
    name: "chief_complaint_form",
    label: "Chief Complaint",
    category: "Medical & Clinical History",
    icon: "🩺",
    description: "Current complaint description and pain scale (1–10).",
  },

  // ── Category 3: Consent & Legal ───────────────────────────────────────────
  {
    id: "data_privacy",
    name: "data_privacy_form",
    label: "Data Privacy (HIPAA)",
    category: "Consent & Legal",
    icon: "🔒",
    description: "Medical data confidentiality statement + digital signature.",
  },
  {
    id: "informed_consent",
    name: "informed_consent_form",
    label: "Informed Consent",
    category: "Consent & Legal",
    icon: "✍️",
    description: "Procedure acknowledgment and risk consent.",
  },
  {
    id: "release_of_info",
    name: "release_of_info_form",
    label: "Release of Information",
    category: "Consent & Legal",
    icon: "📤",
    description: "Authorize sharing of medical records to another institution.",
  },
  {
    id: "advance_directives",
    name: "advance_directives_form",
    label: "Advance Directives",
    category: "Consent & Legal",
    icon: "📜",
    description: "CPR/DNR preferences in case of critical condition.",
  },

  // ── Category 4: Specialty-Specific ────────────────────────────────────────
  {
    id: "mental_health",
    name: "mental_health_form",
    label: "Mental Health Intake",
    category: "Specialty-Specific",
    icon: "🧠",
    description: "Anxiety/depression frequency screening over the past 2 weeks.",
  },
  {
    id: "pediatric",
    name: "pediatric_form",
    label: "Pediatric Intake",
    category: "Specialty-Specific",
    icon: "👶",
    description: "Parent/guardian info, development history, immunization record.",
  },
  {
    id: "obgyn",
    name: "obgyn_form",
    label: "Women's Health (OB/GYN)",
    category: "Specialty-Specific",
    icon: "🌸",
    description: "Last menstrual period, number of pregnancies and deliveries.",
  },
  {
    id: "dental",
    name: "dental_form",
    label: "Dental Intake",
    category: "Specialty-Specific",
    icon: "🦷",
    description: "Dental complaints and last dentist visit.",
  },
  {
    id: "physiotherapy",
    name: "physiotherapy_form",
    label: "Physiotherapy / Chiropractic",
    category: "Specialty-Specific",
    icon: "🦴",
    description: "Body diagram pain marking and pain type.",
  },
  {
    id: "nutrition",
    name: "nutrition_form",
    label: "Nutrition Consultation",
    category: "Specialty-Specific",
    icon: "🥗",
    description: "Weight, height, and primary health goal.",
  },
  {
    id: "skincare",
    name: "skincare_form",
    label: "Skincare & Aesthetics",
    category: "Specialty-Specific",
    icon: "✨",
    description: "Skin type and active skincare products in use.",
  },

  // ── Category 5: Operations & Evaluation ──────────────────────────────────
  {
    id: "infectious_screening",
    name: "infectious_screening_form",
    label: "Infectious Disease Screening",
    category: "Operations & Evaluation",
    icon: "🦠",
    description: "Recent fever/cough and close contact history.",
  },
  {
    id: "telehealth",
    name: "telehealth_form",
    label: "Telehealth Intake",
    category: "Operations & Evaluation",
    icon: "💻",
    description: "Video consultation consent and limitations acknowledgment.",
  },
  {
    id: "satisfaction",
    name: "satisfaction_form",
    label: "Patient Satisfaction Survey",
    category: "Operations & Evaluation",
    icon: "⭐",
    description: "Star-rating survey for doctor/nurse service quality.",
  },
  {
    id: "waitlist",
    name: "waitlist_form",
    label: "Waitlist",
    category: "Operations & Evaluation",
    icon: "⏳",
    description: "Preferred alternative appointment day/time and contact method.",
  },
  {
    id: "refund",
    name: "refund_form",
    label: "Refund Claim",
    category: "Operations & Evaluation",
    icon: "💰",
    description: "Invoice number, refund reason, and bank account details.",
  },
];

export const FORM_CATEGORIES: IntakeFormItem["category"][] = [
  "Registration & Administration",
  "Medical & Clinical History",
  "Consent & Legal",
  "Specialty-Specific",
  "Operations & Evaluation",
];

export const CATEGORY_COLORS: Record<IntakeFormItem["category"], string> = {
  "Registration & Administration": "#2563eb",
  "Medical & Clinical History":   "#059669",
  "Consent & Legal":              "#7c3aed",
  "Specialty-Specific":           "#d97706",
  "Operations & Evaluation":      "#0891b2",
};
